import pygame
pygame.init()
#Константы, магические числа, загрузки, цвета и прочее

infoObject = pygame.display.Info()
WIDTH, HEIGHT = infoObject.current_w, infoObject.current_h
FPS = 60

START_Y = 130
MENU_START_Y = 130
MENU_SPASING_Y = 65
MENU_LABEL_OFFSET_X = 380
MENU_VERTICAL_OFFSET = 5
SETTINGS_HORIZONTAL_OFFSET = 220
RYTM_CORD = 40, 40
CORD_HPBAR = 40, HEIGHT - 175
CORD_GOLD = 350, HEIGHT - 175
WORDS_Y = HEIGHT - 110
CHAR_UP = 20

GROUND_LINE_SIZE = 3
FONT_SIZE = 40
LARGE_FONT_SIZE = 65
ACTIVE_FONT_SIZE = 90
MENU_FONT_SIZE = 32
BUTTON_BORDER_RADIUS = 5
MENU_Y = 40
WORDS_SPACING_X = 20

THORN_WIDTH = 20
THORN_HEIGHT = 20
THORN_DEEP = 15

PLATFORM_BORDER_RADIUS = 20

JUMP = 3
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GRAY = (150, 150, 150)
DARK_GRAY = (100, 100, 100)
LIGHT_GRAY = (220, 220, 220)
GREEN = (34, 177, 76)
RED = (237, 28, 36)
PLAYER_BLUE = (0, 80, 239)
YELLOW = (255, 201, 14)
CYAN_ZONE = (0, 162, 232)
PURPLE = (148, 0, 211)
PROPORTIONAL_COEFFICIENT = 4/3
PLAYER_SIZE = 60
OBSTACLE_SIZE = 60
HEAL_SIZE = 40
HEAL_TEX_SIZE = 70
ZONE_HEIGHT = 90
ZONE_WIDTH = 90
GROUND_Y = HEIGHT - 200
SPAWN_OFFSET_X = 50
BRIDGE_HEIGHT_1 = 130
BRIDGE_HEIGHT_2 = 100
BRIDGE_HEIGHT_3 = 230
DANGER_PLATFORM_HEIGHT = 120
JUMP_VELOCITY_START = -22.5
GRAVITY = 1.5
DIFFICULTY_NAMES = ["Легкий", "Средний", "Сложный", "Веселый"]
DIFFICULTY_MULTIPLIERS = [0.8, 1.0, 1.35, 1.75]
OBSTACLE_DISTANCE_RANGES = [
    (800, 1300), (715, 1235), (525, 975), (500, 1000)
]
OVERLAY_ALPHA = 200
OVERLAY_ALPHA2 = 230
OVERLAY_SPACE = 50

GAME_END_SPACE = 180
STATS_SPACE = 40
STATS_OFFSET = 45
RESTART_OFFSET = 130
MENU_BUTTON_WIDTH = 40
MENU_BUTTON_HEIGHT = 40
MENU_MINUS_OFFSET_X = 60
MENU_PLUS_OFFSET_X = 110
MENU_SPACING_Y = 65
MENU_START_Y_OFFSET = 7 * MENU_SPACING_Y
MENU_BUTTON_GAP_Y = 75
MENU_ACTION_WIDTH = 300
MENU_ACTION_HEIGHT = 60
MENU_START_TEXT = "ЗАПУСТИТЬ"
MENU_QUIT_TEXT = "ВЫХОД"
QUITSTART_OFFSET = 150

WORDS_BANK = [
    ["вода", "небо", "луна", "стол", "стул", "рука", "нога", "глаз", "день", "ночь"],
    ["книга", "дверь", "дождь", "город", "рынок", "ведро", "птица", "актер", "океан", "трава"],
    ["солнце", "дерево", "дорога", "яблоко", "золото", "корова", "собака", "молоко", "ворона", "работа"],
    ["планета", "человек", "корабль", "телефон", "самолет", "капуста", "свобода", "красота", "природа", "картина"]
]

RUSSIAN_ALPHABET = set("абвгдеёжзийклмнопрстуфхцчшщъыьэюя")
WORDS_IN_ROW_COUNT = 4
TARGET_GOLD = 200
PLATFORM_EXT_SIZE = 15

IMAGE_DIR = "images"
TEX_PLAYER = f"{IMAGE_DIR}/Typing_dinO.png"
TEX_OBSTACLE = f"{IMAGE_DIR}/zaborchik_KRIVOY.png"
TEX_ZONE_YELLOW = f"{IMAGE_DIR}/monetka_yellow.png"
TEX_ZONE_BLUE = f"{IMAGE_DIR}/monetka_blue.png"
TEX_BG = f"{IMAGE_DIR}/45908.png"
TEX_HP = f"{IMAGE_DIR}/HEAL_HEART.png"
TEX_THORN = f"{IMAGE_DIR}/THORN_GROUND.png"

ZONE_CHANCE_EASY = 0.75
ZONE_CHANCE_HARD = 0.85
ZONE_MIN_PADDING_X = 10
ZONE_WIDTH_SPAWN = 20
ZONE_WEIGHT_YELLOW = 50
ZONE_WEIGHT_BLUE = 50
ZONE_WEIGHT_YELLOW_FUN = 25
ZONE_WEIGHT_BLUE_FUN = 75
CHUNK_WEIGHTS_EASY = [45, 35, 20]
CHUNK_WEIGHTS_HARD = [30, 50, 20]
GROUND_MIN_LENGTH = 400
GROUND_MAX_LENGTH = 1000
GROUND_OBSTACLE_DENSITY = 250
GROUND_RUSH_OBSTACLE_PADDING = 50
PLAT_MIN_COUNT = 1
PLAT_MAX_COUNT = 6
PLAT_MIN_WIDTH = 200
PLAT_MAX_WIDTH = 600
PLAT_MIN_HEIGHT = 60
PLAT_MAX_HEIGHT = 220
PLAT_THICKNESS = 20
PLAT_OBSTACLE_CHANCE = 0.35
PLAT_MIN_OBSTACLE = 300
PLAT_OBSTACLE_PADDING = 50
GAP_MIN = 50
GAP_MAX_FACTOR = 0.6
PIT_MIN_WIDTH = 100
PIT_MAX_FACTOR = 0.8
PIT_HEIGHT = 40
SPAWN_RESET_OFFSET = 40 

DEF_DIF = 1
DEF_YELLOW_GOLD = 10
DEF_BLUE_GOLD = 10
DEF_CHAR_DAMAGE = 0.2
DEF_OBSTACLE_DAMAGE = 0.5
DEF_HEAL_AMOUNT = 1.0
DEF_RHYTHM_MODE = False
MIN_YELLOW_GOLD = 1
MIN_BLUE_GOLD = 0
MIN_CHAR_DAMAGE = 0.0
MIN_OBSTACLE_DAMAGE = 0.0
MIN_HEAL_AMOUNT = 0.1
CHAR_DAMAGE_STEP = 0.1
OBSTACLE_DAMAGE_STEP = 0.1
HEAL_AMOUNT_STEP = 0.1

MAX_HP = 10.0
PLAYER_START_X = 200
PLAYER_START_Y = GROUND_Y - PLAYER_SIZE
START_GOLD = 0
PIT_COLLISION_MARGIN = 12
BASE_SPEED = 12
MAX_SPEED = 35
PROGRESSION_BASE = 1.0
PROGRESSION_SCALE = 1.5
SECONDS_IN_MINUTE = 60.0

PROGRESSION_BASE = 1.0
PROGRESSION_SCALE = 1.5
BASE_SPEED = 12
MAX_SPEED = 35

PIT_COLLISION_MARGIN = 12
INSTANT_DEATH_IDX = 3
NO_DAMAGE_IDX = 0

HEAL_CHANCE = 0.25
HEAL_MIN_PADDING_X = 50
HEAL_SPAWN_HEIGHT_VARIATION = 100
OBS_PADDING_GROUND = 50
OBS_SPAWN_MIN_OFFSET = 50

ZONE_CHANCE_RUSH = 0.8
ZONE_CHANCE_PLAT= 0.85

TEST_PLAYER_X = 100
TEST_PLAYER_Y = 200
TEST_PLATFORM_X = 50
TEST_PLATFORM_Y = 260
TEST_PLATFORM_WIDTH = 200
TEST_PLATFORM_HEIGHT = 20
TEST_GOLD_START = 50
TEST_HP_LOW = 5.0
TEST_PIT_OFFSET = 50
TEST_PIT_WIDTH = 100
TEST_PIT_HEIGHT = 40
TEST_BUTTON_X = 100
TEST_BUTTON_Y = 100
TEST_BUTTON_WIDTH = 50
TEST_BUTTON_HEIGHT = 30
TEST_YELLOW_GOLD_START = 5

SOUND_DIR = "sounds"

SOUND_JUMP = f"{SOUND_DIR}/jump.wav"
SOUND_COIN = f"{SOUND_DIR}/coin.ogg"
SOUND_DAMAGE = f"{SOUND_DIR}/damage.wav"
SOUND_WIN = f"{SOUND_DIR}/win.wav"
SOUND_LOSE = f"{SOUND_DIR}/lose.wav"
SOUND_OBSTACLE = f"{SOUND_DIR}/obstacle.wav"

SOUND_VOLUME_DEFAULT = 0.5

FONT_PATH = "fonts/Roboto-VariableFont_wdth,wght.ttf"

TEST_OBJ_SIZE = 50
TEST_OBJ_SIZE_SMALL = 10
TEST_MOVE_SPEED = 10
TEST_MOVE_SPEED_SMALL = 5
TEST_ZERO_SPEED = 0
TEST_PLAYER_POS_X = 100
TEST_PLAYER_POS_Y = 100
TEST_JUMP_COUNT = 2
TEST_GRAVITY_FRAMES = 2
TEST_LARGE_DISTANCE = 999999
TEST_PIT_OFFSET_LARGE = 999
TEST_HP_OFFSET = 0.5
TEST_WAIT_TIME = 0.01
TEST_GOLD_AMOUNT = 1
TEST_GOLD_AMOUNT_BLUE = 4
TEST_GOLD_AMOUNT_PLUS = 6
TEST_DAMAGE_BASE = 1.0
TEST_DAMAGE_MINUS = 0.9
TEST_DAMAGE_PLUS = 1.1
TEST_TIME_TOTAL = 10.0
TEST_TIME_TOTAL_SMALL = 5.0
TEST_RECT_EDGE = 10
TEST_RECT_OUTSIDE = 11
TEST_BUTTON_ACTION = "my_action"
TEST_BUTTON_TEXT = "Hello"
TEST_BUTTON_TEXT_DEFAULT = "Test"
TEST_ZONE_TYPE_YELLOW = "yellow"
TEST_ZONE_TYPE_BLUE = "blue"
TEST_ACTION_DIFF_MINUS = "diff_minus"
TEST_ACTION_Y_GOLD_MINUS = "y_gold_minus"
TEST_ACTION_B_GOLD_MINUS = "b_gold_minus"
TEST_ACTION_C_DMG_MINUS = "c_dmg_minus"
TEST_ACTION_O_DMG_MINUS = "o_dmg_minus"
TEST_ACTION_HEAL_MINUS = "heal_minus"
TEST_CHAR_WRONG = "ы"
TEST_CHAR_NON_RUSSIAN = "a"
TEST_OVERLAY_TITLE = "Test"
TEST_OVERLAY_SUBTITLE = "Subtest"
TEST_OVERLAY_COLOR = (0, 0, 0)
TEST_WORDS_BANK_0 = ["вода", "небо", "луна", "стол", "стул", "рука", "нога", "глаз", "день", "ночь"]
TEST_WORDS_BANK_1 = ["книга", "дверь", "дождь", "город", "рынок", "ведро", "птица", "актер", "океан", "трава"]